# Generated by Django 4.2.16 on 2024-11-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(choices=[('profile_images/profile1.jpg', 'profile 1'), ('profile_images/profile2.jpg', 'profile 2'), ('profile_images/profile3.jpg', 'profile 3'), ('profile_images/profile4.jpg', 'profile 4'), ('profile_images/profile5.jpg', 'profile 5'), ('profile_images/profile6.jpg', 'profile 6')], default='profile_images/image1.jpg', max_length=255),
        ),
    ]
