# Generated by Django 4.2.16 on 2024-11-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_visit_count_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stone',
            field=models.IntegerField(default=0),
        ),
    ]
