# Generated by Django 4.2.16 on 2024-11-18 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_like',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='movie_review',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='unique_movie_user_review'),
        ),
        migrations.AddConstraint(
            model_name='moviereview_comment',
            constraint=models.UniqueConstraint(fields=('review', 'reviewuser'), name='unique_review_user_comment'),
        ),
        migrations.DeleteModel(
            name='Movie_like',
        ),
    ]
