# Generated by Django 4.2.16 on 2024-11-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='youtube_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
