# Generated by Django 4.2.16 on 2024-11-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_like_movie_movie_like_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_review',
            name='likes_count',
            field=models.IntegerField(blank=True),
        ),
    ]
