# Generated by Django 4.2.16 on 2024-11-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_youtube_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='words',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
