# Generated by Django 4.2.16 on 2024-11-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_review_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_review',
            name='likes_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
