# Generated by Django 4.2.16 on 2024-11-19 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_review_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
