# Generated by Django 4.2.16 on 2024-11-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='recommend_reasons',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('author', 'date'), name='unique_author_daily_diary'),
        ),
    ]
