# Generated by Django 4.2.16 on 2024-11-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_review_rating'),
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='gpt_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='mood_emoji',
            field=models.CharField(choices=[('emotions/angry.jpg', '분노'), ('emotions/calm.jpg', '평온'), ('emotions/excited.jpg', '신남'), ('emotions/happy.jpg', '행복'), ('emotions/sad.jpg', '슬픔'), ('emotions/sleepy.jpg', '지루')], max_length=100),
        ),
        migrations.AlterField(
            model_name='diary',
            name='recommend_movie',
            field=models.ManyToManyField(blank=True, null=True, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='diary_comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
