# Generated by Django 4.2.16 on 2024-11-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_diary_recommend_movie_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='recommend_movie_titles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
