# Generated by Django 4.2.16 on 2024-11-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_alter_diary_recommend_movie_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='analysis_emotion',
            field=models.TextField(blank=True),
        ),
    ]
